### PR TITLE
Added links to table references

### PR DESCRIPTION
**Pull request by 2016rshah**
Rather than making the reader scroll all the way down every time they can just click a link to go to the table they are looking for.

### CODE REVIEW

**Comment by pthariensflame** [comment]
You could use Markdown's built-in link syntax, rather than relying on the underlying HTML; _e.g._, `[my link text here](http://my.url.here/)`.

**Comment by 2016rshah** [comment]
Is there any reason the Markdown syntax would be better than just using the underlying HTML? That is what I tried initially but for some reason it doesn't play nicely with the relative path of `#7--reference-tables` so I just reverted to the `a` tag but if there is some reason why that is bad practice I can look into trying to make the Markdown syntax work. 

I can't think of any benefit though especially because Markdown just processes it into HTML anyways so the two methods should be equivalent, right?

**Comment by pthariensflame** [comment]
Yeah, they should be equivalent.  It's really a stylistic issue, rather than anything concrete.  Since you've now stated that you've tried it and couldn't get it to work, I'll just back off quietly.  :P

**Comment by 2016rshah** [comment]
No problem, thanks for the suggestion though!

**Comment by aaxios** [comment]
This Pull Request is being denied. Thank you for your engagement.

**Pull request closed without merging**
