### PR TITLE
Add datapackage.json

### PR DESCRIPTION
**Pull request by acouch**
This PR adds a DataPackage.json file to make the contents of this repo more easily discoverable and usable.  See: http://data.okfn.org/standards for more details.

### CODE REVIEW

**Comment by jessebeach** [comment]
:+1:

**Comment by cew821** [comment]
@acouch could you provide more insight into how you generated this file? We are potentially interested in this, but want to better understand the implications of keeping the schema file up to date (both as the schema itself evolves, and the data potentially changes).

**Comment by acouch** [comment]
@cew821 Thanks for taking a look. I generated the schema file with: http://data.okfn.org/tools/create

That project is a work in progress and there are some tickets to do things like fix the license field and be able to generate multiple files at once: https://github.com/okfn/datapackage-init/issues

@rgrp Could answer more questions. Would be interesting to hear what improvements to that tool would facilitate adopting datapackage.json

**Comment by rufuspollock** [comment]
@cew821 delighted to hear of your interest. More about "Frictionless Data" in general, and "Data Packages" specifically on: http://data.okfn.org/ 

Intro to Data Package: http://data.okfn.org/doc/data-package

There's a whole bunch of data packaged datasets at: https://github.com/datasets

**Comment by aaxios** [comment]
This Pull Request is being denied. Thank you for your engagement.

Consider creating a new pull request against the the 2016 branch.

**Pull request closed without merging**
